# Wazihub Soil Moisture Prediction Challenge

Import libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import datetime as dt

% matplotlib inline

UsageError: Line magic function `%` not found.

Import data

In [1]:
import os

os.getcwd()

'C:\\Users\\Aymen\\Desktop\\Wazihub Soil Moisture Prediction Challenge'

In [4]:
maize = pd.read_csv('Context_Data_Maize.csv')
peanuts = pd.read_csv('Context_Data_Peanuts.csv')
sample = pd.read_csv('SampleSubmission.csv')
train = pd.read_csv('Train.csv')
var_defs = pd.read_csv('/VariableDefinitions.csv')

FileNotFoundError: File b'/VariableDefinitions.csv' does not exist

In [4]:
train.head()

,timestamp,Soil humidity 1,Irrigation field 1,Soil humidity 2,Irrigation field 2,Soil humidity 3,Irrigation field 3,Soil humidity 4,Irrigation field 4,Air temperature (C),Air humidity (%),Pressure (KPa),Wind speed (Km/h),Wind gust (Km/h),Wind direction (Deg)
0,2019-02-23 00:00:00,67.92,0.0,55.72,0.0,-1.56,1.0,26.57,1.0,19.52,55.04,101.50,2.13,6.30,225.00
1,2019-02-23 00:05:00,67.89,0.0,55.74,0.0,-1.51,1.0,26.58,1.0,19.49,55.17,101.50,2.01,10.46,123.75
2,2019-02-23 00:10:00,67.86,0.0,55.77,0.0,-1.47,1.0,26.59,1.0,19.47,55.30,101.51,1.90,14.63,22.50
3,2019-02-23 00:15:00,67.84,0.0,55.79,0.0,-1.42,1.0,26.61,1.0,19.54,54.20,101.51,2.28,16.08,123.75
4,2019-02-23 00:20:00,67.81,0.0,55.82,0.0,-1.38,1.0,26.62,1.0,19.61,53.09,101.51,2.66,17.52,225.00

In [17]:
sample.head()

                                      ID  Values
0  2019-03-25 22:50:00 x Soil humidity 1     NaN
1  2019-03-25 22:55:00 x Soil humidity 1     NaN
2  2019-03-25 23:00:00 x Soil humidity 1     NaN
3  2019-03-25 23:05:00 x Soil humidity 1     NaN
4  2019-03-25 23:10:00 x Soil humidity 1     NaN

In [8]:
maize.head()

,Date,Min_Temp,Max_Temp,Humidity,Wind_Speed,Solar_Irradiance,Sun,Kc,ETc,ETo,Rainfall,Water_Need_1day,Water_Need_2days,Water_Need_3days
0,6-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,NaN,NaN,NaN
1,7-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,NaN,NaN,NaN
2,8-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,NaN,NaN,NaN
3,9-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,NaN,NaN,NaN
4,10-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,NaN,NaN,NaN

In [10]:
peanuts.head()

,Date,Min_Temp,Max_Temp,Humidity,Wind_Speed,Solar_Irradiance,Sun,Kc,ETc,ETo,Rainfall,Water_Need_1day,Water_Need_2days,Water_Need_3days,Unnamed: 14
0,6-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,0.0,NaN,NaN,NaN
1,7-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,0.0,NaN,NaN,NaN
2,8-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,0.0,NaN,NaN,NaN
3,9-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,10-Feb,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.0,0.0,NaN,NaN,NaN

In [12]:
var_defs

   Variabe Definitions                                         Unnamed: 1
0                  NaN                                                NaN
1                Train                                                NaN
2            timestamp          Time of recording in yyyy-mmm-dd hh-mm-ss
3      Soil_humidity_1                           Soil humidity of field 1
4   Irrigation field 1                  1=irrigation on, 0=irrigation off
5      Soil_humidity_2                           Soil humidity of field 2
6   Irrigation field 2                  1=irrigation on, 0=irrigation off
7      Soil_humidity_3                           Soil humidity of field 3
8   Irrigation field 3                  1=irrigation on, 0=irrigation off
9      Soil_humidity_4                           Soil humidity of field 4
10  Irrigation field 4                  1=irrigation on, 0=irrigation off
11     Air_temperature           Temprature of the air in degrees Celcius
12        Air_humidity                                Humidity of the air
13        Air_Pressure                Pressure of the air in kilo pascals
14          Wind_speed           Speed of the wind in kilometers per hour
15           Wind_gust  Speed of the gusts of wind in kilometers per hour
16       Wind_irection        Direction of the wind in degrees from North
17                 NaN                                                NaN
18             Context                                                NaN
19                Date                                  Date (MM/DD/YYYY)
20            Min_Temp    Minimum daily temperature measured in celsius\n
21            Max_Temp    Maximum daily temperature measured in celsius\n
22            Humidity                               Percent air humidity
23          Wind_Speed           Wind speed measured in meters per second
24    Solar_Irradiance  The power per unit area (Watt per square metre...
25                 Sun  Radiant energy emitted by the sun measured in ...
26                  Kc  Crop coefficient Kc. A property of plants used...
27                 ETc  The evapotranspiration rate observed in the cr...
28                 ETo  The evapotranspiration rate observed for a wel...
29            Rainfall                                   Rainfall per day
30     Water_Need_1day  The water needs of the crop measured (Evapotra...
31    Water_Need_2days  The water needs of the crop measured (Evapotra...
32    Water_Need_3days  The water needs of the crop measured (Evapotra...

In [19]:
train["timestamp"] = pd.to_datetime(train["timestamp"])
train.set_index("timestamp", inplace=True)

In [31]:
train.loc["2019-05-28":"2019-05-31"]["Irrigation field 4"].unique()

array([ 0.,  1., nan])